/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ActivityService } from "../activity.service";
import { ActivityCreateInput } from "./ActivityCreateInput";
import { Activity } from "./Activity";
import { ActivityFindManyArgs } from "./ActivityFindManyArgs";
import { ActivityWhereUniqueInput } from "./ActivityWhereUniqueInput";
import { ActivityUpdateInput } from "./ActivityUpdateInput";
import { ScoreFindManyArgs } from "../../score/base/ScoreFindManyArgs";
import { Score } from "../../score/base/Score";
import { ScoreWhereUniqueInput } from "../../score/base/ScoreWhereUniqueInput";
import { ActivityDto } from "../ActivityDto";

export class ActivityControllerBase {
  constructor(protected readonly service: ActivityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Activity })
  async createActivity(
    @common.Body() data: ActivityCreateInput
  ): Promise<Activity> {
    return await this.service.createActivity({
      data: {
        ...data,

        teacher: data.teacher
          ? {
              connect: data.teacher,
            }
          : undefined,
      },
      select: {
        assignedDate: true,
        createdAt: true,
        id: true,

        teacher: {
          select: {
            id: true,
          },
        },

        templateId: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Activity] })
  @ApiNestedQuery(ActivityFindManyArgs)
  async activities(@common.Req() request: Request): Promise<Activity[]> {
    const args = plainToClass(ActivityFindManyArgs, request.query);
    return this.service.activities({
      ...args,
      select: {
        assignedDate: true,
        createdAt: true,
        id: true,

        teacher: {
          select: {
            id: true,
          },
        },

        templateId: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Activity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async activity(
    @common.Param() params: ActivityWhereUniqueInput
  ): Promise<Activity | null> {
    const result = await this.service.activity({
      where: params,
      select: {
        assignedDate: true,
        createdAt: true,
        id: true,

        teacher: {
          select: {
            id: true,
          },
        },

        templateId: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Activity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateActivity(
    @common.Param() params: ActivityWhereUniqueInput,
    @common.Body() data: ActivityUpdateInput
  ): Promise<Activity | null> {
    try {
      return await this.service.updateActivity({
        where: params,
        data: {
          ...data,

          teacher: data.teacher
            ? {
                connect: data.teacher,
              }
            : undefined,
        },
        select: {
          assignedDate: true,
          createdAt: true,
          id: true,

          teacher: {
            select: {
              id: true,
            },
          },

          templateId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Activity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteActivity(
    @common.Param() params: ActivityWhereUniqueInput
  ): Promise<Activity | null> {
    try {
      return await this.service.deleteActivity({
        where: params,
        select: {
          assignedDate: true,
          createdAt: true,
          id: true,

          teacher: {
            select: {
              id: true,
            },
          },

          templateId: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/scores")
  @ApiNestedQuery(ScoreFindManyArgs)
  async findScores(
    @common.Req() request: Request,
    @common.Param() params: ActivityWhereUniqueInput
  ): Promise<Score[]> {
    const query = plainToClass(ScoreFindManyArgs, request.query);
    const results = await this.service.findScores(params.id, {
      ...query,
      select: {
        activity: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateRecorded: true,
        id: true,
        score: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/scores")
  async connectScores(
    @common.Param() params: ActivityWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        connect: body,
      },
    };
    await this.service.updateActivity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/scores")
  async updateScores(
    @common.Param() params: ActivityWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        set: body,
      },
    };
    await this.service.updateActivity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/scores")
  async disconnectScores(
    @common.Param() params: ActivityWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        disconnect: body,
      },
    };
    await this.service.updateActivity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/activity")
  @swagger.ApiOkResponse({
    type: ActivityDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async AssignActivity(
    @common.Body()
    body: ActivityDto
  ): Promise<ActivityDto> {
    return this.service.AssignActivity(body);
  }

  @common.Get("/activities")
  @swagger.ApiOkResponse({
    type: ActivityDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetActivities(
    @common.Body()
    body: ActivityDto
  ): Promise<ActivityDto[]> {
    return this.service.GetActivities(body);
  }
}
